### ISSUE TITLE
[Developer] - Review and test API Design Lab Unit 

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#10]
**Description**
The developer will directly import the spec since the contracts are already created.

The spec will have three endpoints:
```
GET /locations
GET /locations/{id}
POST /locations
```

**Comment by VinayBhalerao** [comment]
Per @weimeilin79 request, add `GET /location/phone/{id}` to the spec

**Comment by VinayBhalerao** [comment]
Added spec https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/docs/labs/developer-track/resources/Locations.yaml

**Comment by VinayBhalerao** [comment]
Re-opening the issue:
Update the spec with version 2.0

**Comment by VinayBhalerao** [comment]
Added the spec [here](https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/docs/labs/developer-track/resources/Locations.yaml)
