### ISSUE TITLE
Citizen Integrator Lab 3 Step 3 - very confusing

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#107]
Not obvious that user is supposed to do command line curl. Previous labs used Online Curl...

Not clear 2 substitutions in POST

Validation returns different data, so not obvious if or what my post did

**Comment by VinayBhalerao** [comment]
Closed via https://github.com/RedHatWorkshops/dayinthelife-integration/pull/111
