### ISSUE TITLE
Citizen Integration Lab 5 Step 3 - replace GUID URL with correct url

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#109]

**Comment by VinayBhalerao** [comment]
Fixed https://github.com/RedHatWorkshops/dayinthelife-integration/commit/22df5b245bc1da3be3eae974213133e452a9c95d

I'll still keep this issue open since few screenshots need to be replaced.

**Comment by VinayBhalerao** [comment]
Updated and fixed in https://github.com/RedHatWorkshops/dayinthelife-integration/issues/110
