### ISSUE TITLE
Citizen Integration Lab 5 Step 3.12 - replace GUID URL with correct url and update screenshot

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#110]

**Comment by VinayBhalerao** [comment]
I think it's related to https://github.com/RedHatWorkshops/dayinthelife-integration/issues/109#issuecomment-433297913

**Comment by VinayBhalerao** [comment]
fixed via https://github.com/RedHatWorkshops/dayinthelife-integration/commit/22df5b245bc1da3be3eae974213133e452a9c95d#diff-0246b9abe20a1daa20632dfbb561ef98, https://github.com/RedHatWorkshops/dayinthelife-integration/commit/f6eca9a48279ed121b59cae210bd227c3452a24f#diff-0246b9abe20a1daa20632dfbb561ef98
