### ISSUE TITLE
Citizen Integrator Lab 6 Example needs to be updated to remove GUID urls / match current URL format

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#113]

**Comment by VinayBhalerao** [comment]
@sigreen / @weimeilin79 Did either of you fixed this? I see the examplef URL fine

Lab 6: https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/docs/labs/developer-track/lab06

`curl -X POST http://threesclae-automate-international.dil.opentry.me/threescale/automate/829405ec3d2dd0f91aa8435347827135c323c69757dd2dfb49ed41aa8ceb13ef/user26/dil.opentry.me`
