### ISSUE TITLE
Update resources `Locations.yaml` with openAPI 3.0.2

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#115]
Citizen track Lab 01:

`If you are planning to skip this lab and follow the next one, here is a link to the specification generated in this lab.`

It redirects to https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/docs/labs/citizen-integrator-track/resources which uses swagger 2.0. We should update it to OAI 3.0.2

**Comment by VinayBhalerao** [comment]
Closed https://github.com/RedHatWorkshops/dayinthelife-integration/commit/faa1124475412f5792d1b662ebb925166fd0294d

**Comment by VinayBhalerao** [comment]
@sigreen Kindly verify if we need OAI 3.0.2 and not swagger 2.0. Close if all good.

**Comment by sigreen** [comment]
We agreed with @weimeilin79 that we'd use OAI 3.0.2 for citizen-integrator track and swagger 2.0 for developer track.
