### ISSUE TITLE
User 39 is stuck / Zombie user cleanup

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#116]
Tried to login with User39 and it was still stuck at 80%.  So…  I went into OCP as cluster admin and attempted to delete project user39-walkthrough-projects.  Still stuck on removing some enmasse project.  Not even sure why enmasse is provisioned since we don’t use it any labs.  Anyway we can have better control on cleaning-up zombie users?

**Comment by maleck13** [comment]
@sigreen is this still an issue. looking at that namespace it seems fine now?

**Comment by sigreen** [comment]
User is no longer stuck.  Took an hour or so to delete project and attempt re-login
