### ISSUE TITLE
[Developer] - Review and test the API Mockup lab unit 

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#12]
Lab unit - API Mockup (TBD) - Integrator Track

Step 0: Setup the collaboration environment using Git (Gogs)
Step 1: Create a Microcks Job
Step 2: Test the REST Mock Service

https://github.com/hguerrero/3scale-api-workshop/tree/master/docs/labs/lab102

**Comment by VinayBhalerao** [comment]
@kasriniv do you want me to take over this lab?

**Comment by sigreen** [comment]
Lab content included by merge in both tracks
