### ISSUE TITLE
Eclipse Che login screen says OpenShift - should say Eclipse Che

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#122]
@jasonmadigan

**Comment by jasonmadigan** [comment]
@maleck13 @aidenkeating ^

**Comment by scranton** [comment]
If its the security realm name, then may I suggest using Red Hat Service Explorer (to be consistent with web app) or use Integreatly as that's then name of the whole stack.

Listing an individual product is confusing as it made me think I clicked the wrong link, i.e. OpenShift console versus Eclipse Che.

**Comment by weimeilin79** [comment]
No complains
