### ISSUE TITLE
API Developer Lab 3 Step 4.14 - bug? no results returned

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#124]
I'm not getting any results returned

**Comment by weimeilin79** [comment]
I went over your code, the @Component is missing from the class. (In step 4.8) That causes your Camel route not picked up by Spring.  Therefore nothing returns.

**Comment by scranton** [comment]
User error, got it. I'll try again today.

I will say that the current instructions are quite complex as your adding and updating code around existing code, and the '...' in the middle of the code snippet implying the existing code isn't that obvious. May want to break up the steps to make the different additions more obvious, and to provide a little commentary about why your adding the different bits of code, i.e. add @component so that Spring Boot picks up this code and runs it during Spring Boots boot up process....

**Comment by sigreen** [comment]
Working on this.  I will update the template projects to include Java comments that describe each code insertion.

**Comment by sigreen** [comment]
I've done my best to breakdown the code into smaller chokes and add more steps.  Hopefully this is clear enough.
