### ISSUE TITLE
Review and test the API Management lab unit 

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#13]
Lab 4 - API Management + Securing your service using API Key - All Tracks 

Part 1 - API Definition 

Step 1: Define your API Proxy
Step 2: Define your API Policies
Step 3: Configure the Upstream Endpoint

Part 2a - API Security
	
Step 1: Secure your API using API Key 
Step 2: tbd 
Step 3: Configure 3scale Integration
Step 4: Create a Test App

Part 3b - API Portal (Publish) - (Integrator Track) - Test your API portal 

Step 1: 
Step 2: 
Step 3: 

https://github.com/hguerrero/3scale-api-workshop/tree/master/docs/labs/lab03

**Comment by VinayBhalerao** [comment]
Closing since all the assests from Hugo's repo are migrated and the lab is tested successfully
