### ISSUE TITLE
[Integreatly] - 3scale `apicast-staging` and `apicast-production` routes are incorrect

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#131]
The auto generated routes per our script are in format

**POD**
apicast-staging: `https://wt2-evals01-example-com-3scale.dil.opentry.me `
apicast-prod: I cannot see a route created for this.

**Screenshot from OCP**
![openshift_web_console](https://user-images.githubusercontent.com/7827135/47546449-38910900-d8a6-11e8-8675-336509f6e2d9.png)

**Expected**

3scale routes should in format

**PODs**
apicast-staging: `https://api-user1-apicast-staging.dil.opentry.me:443`
apicast-production:  `https://api-user1-apicast-production.dil.opentry.me:443`

**Screenshot from 3scale integration page**
![integrations_-_update___red_hat_3scale_api_management](https://user-images.githubusercontent.com/7827135/47546500-670ee400-d8a6-11e8-9947-144d269faed2.png)

**Comment by maleck13** [comment]
So the ```https://wt2-evals01-example-com-3scale.dil.opentry.me ``` routes are for one of our walkthroughs. 

I see other routes that were created by your scripts there too. If you go to the 3scale namespace and to application routes you should see them. They are named
```system-developer-user50-route``` etc and were created by the following ansible playbook
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/create-tenants.yml#L42

**Comment by jasonmadigan** [comment]
@VinayBhalerao ^

**Comment by VinayBhalerao** [comment]
I had a quick chat with @hguerrero on this issue

The best way going forward is:
1. Delete all the unnecessary routes for `apicast-staging` eg: wt2-evals01-example-com-3scale.dil.opentry.me 
2. Delete the existing apicast-router value `https://apicast-wildcard.dil1.opentry.me` 
3. Create a new route for apicast-router value with `*.amp.<ocp_domain>` eg: *.amp.dil.opentry.me` as part of your 3scale installation script

**Comment by hguerrero** [comment]
> I had a quick chat with @hguerrero on this issue
> 
> The best way going forward is:
> 
> 1. Delete all the unnecessary routes for `apicast-staging` eg: wt2-evals01-example-com-3scale.dil.opentry.me
> 2. Delete the existing apicast-router value `https://apicast-wildcard.dil1.opentry.me`
> 3. Create a new route for apicast-router value with `*.amp.<ocp_domain>` eg: *.amp.dil.opentry.me` as part of your 3scale installation script

Just for the last point the new route should have the following hostname: `apicast-wildcard.amp.<opc_domain>` and be of type Subdomain. It's required that the OCP cluster routers are enabled to receive wildcard routes.

**Comment by VinayBhalerao** [comment]
This is resolved. Closing.
