### ISSUE TITLE
Developer Lab 06 - Automate command doesn't work

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#132]
As per the step, https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/docs/labs/developer-track/lab06#step-2-start-managing-your-apis fails to automate the setup

**Command**
curl -X POST http://threescale-automate-international.dil.opentry.me/threescale/automate/a5144112f7f6399660b5907e4a4fa2123507706fa7af5d610c2866d126b939e4/user1/dil.opentry.me

But it returned error `Application not found`

cc @weimeilin79

**Comment by weimeilin79** [comment]
@VinayBhalerao 
But I saw your attempted and it's successful. 
05:44:02.434 [XNIO-3 task-7] INFO  route3 - Service : [56] and Plan [216] and Account []
--
  | 05:44:02.435 [XNIO-3 task-7] INFO  route3 - {Accept=*/*, apiToken=a5144112f7f6399660b5907e4a4fa2123507706fa7af5d610c2866d126b939e4, breadcrumbId=ID-threesclae-automate-1-hrdsc-1540489940796-0-12, Cache-Control=max-age=0, private, must-revalidate, CamelHttpMethod=GET, CamelHttpQuery=access_token=a5144112f7f6399660b5907e4a4fa2123507706fa7af5d610c2866d126b939e4, CamelServletContextPath=/threescale/automate/{apiToken}/{userid}/{openshiftappurl}, Content-Type=application/xml; charset=utf-8, Date=Fri, 26 Oct 2018 05:44:02 GMT, ETag=W/"7b10e7f8aca6352ab2323bc346caa4ce", Forwarded=for=10.0.172.83;host=threesclae-automate-international.dil.opentry.me;proto=http, Location=https://user1-admin.dil.opentry.me/admin/api/services/56/application_plans?id=216 , openshiftappurl=dil.opentry.me, planid=216, serviceid=56, Set-Cookie=59bd377f96d90dfdaff9be480304ea97=d547d3c943a2b060a9384913def10d11; path=/; HttpOnly, Strict-Transport-Security=max-age=15552000, Transfer-Encoding=chunked, userid=user1, Vary=Accept-Encoding, X-Content-Type-Options=nosniff, X-Forwarded-For=10.0.172.83, X-Forwarded-Host=threesclae-automate-international.dil.opentry.me, X-Forwarded-Port=80, X-Forwarded-Proto=http, X-Frame-Options=DENY, X-Request-Id=9cc88537-24ec-41bf-aafd-f46de5a7429e, X-Runtime=0.077752, X-Served-By=system-app-1-dm2v5, X-XSS-Protection=1; mode=block}
  | 05:44:03.436 [XNIO-3 task-7] INFO  o.a.c.util.jsse.SSLContextParameters - Available providers: SUN version 1.8.
  | 05:44:03.436 [XNIO-3 task-7] INFO  o.a.c.util.jsse.SSLContextParameters - Available providers: SUN version 1.8.
  | 05:44:03.436 [XNIO-3 task-7] INFO  o.a.c.component.http4.HttpComponent - Created ClientConnectionManager org.apache.http.impl.conn.PoolingHttpClientConnectionManager@60507048
  | 05:44:04.745 [XNIO-3 task-7] INFO  o.a.c.util.jsse.SSLContextParameters - Available providers: SUN version 1.8.
  | 05:44:04.745 [XNIO-3 task-7] INFO  o.a.c.util.jsse.SSLContextParameters - Available providers: SUN version 1.8.
  | 05:44:04.746 [XNIO-3 task-7] INFO  o.a.c.component.http4.HttpComponent - Created ClientConnectionManager org.apache.http.impl.conn.PoolingHttpClientConnectionManager@60140307
  | 05:44:06.105 [XNIO-3 task-7] INFO  o.a.c.util.jsse.SSLContextParameters - Available providers: SUN version 1.8.
  | 05:44:06.105 [XNIO-3 task-7] INFO  o.a.c.util.jsse.SSLContextParameters - Available providers: SUN version 1.8.
  | 05:44:06.105 [XNIO-3 task-7] INFO  o.a.c.component.http4.HttpComponent - Created ClientConnectionManager org.apache.http.impl.conn.PoolingHttpClientConnectionManager@c554b58
  | 05:44:06.217 [XNIO-3 task-7] INFO  route3 - return---->  {"policies_config":[{"name":"cors","version":"builtin","configuration":{"allow_headers":["Authorization"],"allow_credentials":true,"allow_methods":["GET","OPTIONS"],"allow_origin":"*"},"enabled":true},{"name":"apicast","version":"builtin","configuration":{},"enabled":true}]}

**Comment by VinayBhalerao** [comment]
yeah I attempted both host `threesclae-automate-international.dil.opentry.me` and `threesclae-automate-international.dil.opentry.me` and I think it failed for the latter.

We should fix the script to use `threescale`
