### ISSUE TITLE
Screenshot different than what is provided to user.

### ISSUE THREAD

**Issue by nickschuetz** [RedHatWorkshops/dayinthelife-integration#136]
In the Citizen Integrator Track Lab 1:

https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/docs/labs/citizen-integrator-track/lab01#lab-1

The following screenshot varies from what the student is actually provided:

https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/docs/labs/citizen-integrator-track/lab01/images/design-52.png

What user gets:

![screen shot 2018-10-26 at 12 58 38 pm](https://user-images.githubusercontent.com/21105624/47584127-f2c45700-d91e-11e8-8984-fa45ba36e33e.png)

**Comment by VinayBhalerao** [comment]
I'll verify this once the new cluster is provisioned

**Comment by sigreen** [comment]
Screen shot updated
