### ISSUE TITLE
Citizen Integrator Lab 1/Step 1 - Update Screenshots

### ISSUE THREAD

**Issue by mbogoevici** [RedHatWorkshops/dayinthelife-integration#137]
While instructions indicate that the API name to use should follow the format "Location-UserX", the screenshots use "Location UserX" (space instead of hyphen). If the user mistakingly chooses the latter format, they will have issues down the road, when the "Location-UserX" format is expected. 

Maybe add an additional warning here on keeping with this identifier throughout the lab.

**Comment by VinayBhalerao** [comment]
Fixed via https://github.com/RedHatWorkshops/dayinthelife-integration/pull/154
