### ISSUE TITLE
Citizen Integrator/Lab 3/Step 3 - clarify variables/samples

### ISSUE THREAD

**Issue by mbogoevici** [RedHatWorkshops/dayinthelife-integration#143]
Multiple issues:

a) Item 1 is duplicated - renumber sequence

b) Remove the URL from the sample - value is incorrect and confusing (will be different for each user). Just refer to value copied in item 1 (Copy external URL). Use a table for the options and make it clearer where the value needs to be replaced. Maybe use something like `<user-number>` to make it more obvious.

**Comment by VinayBhalerao** [comment]
Partially fixed https://github.com/RedHatWorkshops/dayinthelife-integration/commit/a3bc4a1593ff48b5123d40bb46b0e4e8cb9692e6

**Comment by VinayBhalerao** [comment]
Fixed https://github.com/RedHatWorkshops/dayinthelife-integration/commit/a91df04d185cd3d5359f842e6e9c335026872e2a
