### ISSUE TITLE
Citizen Integration: Lab 2 Gogs - New Migration Minor Syntax Error

### ISSUE THREAD

**Issue by nickschuetz** [RedHatWorkshops/dayinthelife-integration#145]
The Owner in the New Migration should be lowercase u not uppercase as stated in the instructions. This is step 4.

Fill in the information of the repository migration with the following values:

Owner: **U**serX

Should be

Owner: userX

**Comment by VinayBhalerao** [comment]
Removed the gogs section https://github.com/RedHatWorkshops/dayinthelife-integration/commit/b5448739eaf44c59c6c6be6357c668ecc9160ba6. So no logner valid.
