### ISSUE TITLE
Lab 3 Step 2: Create webhook integration Needs Description

### ISSUE THREAD

**Issue by nickschuetz** [RedHatWorkshops/dayinthelife-integration#146]
Currently item #1 in Step 2 only has a placeholder stating "Description goes here"

**Comment by VinayBhalerao** [comment]
I don't remember why we added that text. Removed it https://github.com/RedHatWorkshops/dayinthelife-integration/commit/d1db66809baf562653fd2723f9a7a4ac1900ec8b
