### ISSUE TITLE
Lab 3 Step 2 Item 5 Needs a "Done" direction.

### ISSUE THREAD

**Issue by nickschuetz** [RedHatWorkshops/dayinthelife-integration#147]
It simply says Screenshot at the moment. Then the next items skips to the next screen.

**Comment by VinayBhalerao** [comment]
Fixed https://github.com/RedHatWorkshops/dayinthelife-integration/commit/c4f5c745da97ea00f44528eef23d05c7fec88444

Is it better now?

**Comment by VinayBhalerao** [comment]
Added more similar edits https://github.com/RedHatWorkshops/dayinthelife-integration/commit/b0d0326c787f12c54e3f452eef988162c39f6415
