### ISSUE TITLE
Developer/Lab 3/Step 4.4 - Yaml in instructions, JSON in POM

### ISSUE THREAD

**Issue by mbogoevici** [RedHatWorkshops/dayinthelife-integration#158]
The instructions for the current lab reference a YAML Swagger file, but the POM of the imported project is pre-configured with a reference to a JSON file, i.e.:

      <plugin>
		  <groupId>org.apache.camel</groupId>
		  <artifactId>camel-restdsl-swagger-plugin</artifactId>
		  <version>2.21.0</version>
		  <configuration>
		    <specificationUri>src/spec/location.json</specificationUri>
		    <className>CamelRoutes</className>
		    <packageName>com.redhat</packageName>
		    <outputDirectory>src/main/java</outputDirectory>      
		  </configuration>
	  </plugin>
 
Ideally we should be consistent and avoid forcing the attendee fix this (it's not obvious why they should do it).

**Comment by sigreen** [comment]
@weimeilin79 : can you please update location-service/pom.xml with the following:

  <plugin>
	  <groupId>org.apache.camel</groupId>
	  <artifactId>camel-restdsl-swagger-plugin</artifactId>
	  <version>2.21.0</version>
	  <configuration>
	    <specificationUri>${project.basedir}/src/spec/location.yaml</specificationUri>
	    <className>CamelRoutes</className>
	    <packageName>com.redhat</packageName>
	    <outputDirectory>${project.basedir}/src/main/java</outputDirectory>      
	  </configuration>
  </plugin>

**Comment by weimeilin79** [comment]
DONE and verified! http://gogs.dil1.opentry.me/user10/dayintheliferepo/src/master/location-service/pom.xml
