### ISSUE TITLE
Develop the API Integration (Fuse) lab unit 

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#16]
Lab 3 - API Implementation (Developer Tracks)

Step 1: Rest DSL 
Step 2: Composite Integration (Broker /API)
Step 3: Fuse Online Salesforce to DB

**Comment by weimeilin79** [comment]
Lab 3 - API Implementation (Developer Tracks)

Step 1: Swagger to Rest DSL (From DB)
Step 2: SOAP to REST 
Step 3: Fuse Online (POST)

**Comment by VinayBhalerao** [comment]
PR https://github.com/RedHatWorkshops/dayinthelife-integration/pull/40

**Comment by sigreen** [comment]
Merged by vinay into lab content
