### ISSUE TITLE
Add a single reference page with links/passwords/etc

### ISSUE THREAD

**Issue by mbogoevici** [RedHatWorkshops/dayinthelife-integration#165]
On the Agenda page, or as a separate 'Prerequisites' module, provide a list of all the links to the resources used in the lab: Apicurio, Gogs, 3scale, Microcks, Red Hat Solution Explorer, OpenShift and corresponding usernames and passwords - possibly lab instructions as well. This would provide an easy reference for the attendees as they navigate through the lab - and they can always return to it in case they need guidance on the various steps.

**Comment by weimeilin79** [comment]
Security issue.

**Comment by weimeilin79** [comment]
The links are already in the Integreatly home page, and the links will not be the same depending on the host, should we just point to Integreatly home page?
