### ISSUE TITLE
Review and test the advanced API Security lab unit 

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#18]
Part 2 (Advanced lab) - API Security - Configure and setup OpenID Connect
	
Step 1: Get Red Hat Single Sign On Service Account Credentials
Step 2: Add User to Realm
Step 3: Configure 3scale Integration
Step 4: Create a Test App

https://github.com/hguerrero/3scale-api-workshop/tree/master/docs/labs/lab04

**Comment by VinayBhalerao** [comment]
Decide to have `user_key` or `open-id` connect in single or both labs. Pending review.
cc @yossiko24

**Comment by VinayBhalerao** [comment]
Closing. Decided to use `openID` connect
