### ISSUE TITLE
[IMPORTANT] Adding user namespaces and www app

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#181]
As we are finalizing the the lab content, we realized there is a need to create a user namespace for each user. As well as creating the International Inc in the namespace. 

So I update the user_project main.yml and also turn on the user_project in the integreatly inventory. Can you please check if I did it right? Can can you please re-run it on DIL? Thanks!

It is related to this issue.
https://github.com/RedHatWorkshops/dayinthelife-integration/issues/178

@jasonmadigan @aidenkeating

**Comment by jasonmadigan** [comment]
@aidenkeating to check

**Comment by aidenkeating** [comment]
@jasonmadigan @weimeilin79 I had to make a change to the integreatly playbook which I'll make a PR for shortly. But the changes are included in DIL and DIL1 now
