### ISSUE TITLE
Review and test the API publish lab unit 

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#19]
Lab 3 - Publish your API - API Portal - Configure & Setup portal (Operations Track)

Step 1: Customizing Developer Portal
Step 2: Register New Accounts Using Developer Portal
Step 3: Login to Developer Portal

https://github.com/hguerrero/3scale-api-workshop/tree/master/docs/labs/lab05

**Comment by VinayBhalerao** [comment]
Closing. Lab 03 is migrated and tested successfully.
