### ISSUE TITLE
Dev track Lab07 2.7 screenshot it confusing

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#194]
There is a red arrow pointing to the sso Location API. This is confusing users as they click and unable to update the redirect URL.  Please modify screenshot to point to 'developers API' instead as that is the correct link

**Comment by VinayBhalerao** [comment]
Fixed via https://github.com/RedHatWorkshops/dayinthelife-integration/commit/6b8b56d024232fc7c6679db98966d5949fb98c0a
