### ISSUE TITLE
Test Agile Integration workshop deployment (RHPDS) - User Side 

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#20]
Test the completed workshop deployment on RHPDS from the user point of view. 

1. Register to the workshop
2. Receive workshop credentials
3. Access your workshop environment

**Comment by VinayBhalerao** [comment]
Closing. Using Integreatly platform. 

Yossi to work with field marketing team to create a google doc for participants to access the credentials.
