### ISSUE TITLE
Assign User Names via Paper and Consolidate Workshop Links on GitHub (bit.ly)

### ISSUE THREAD

**Issue by mhockelberg** [RedHatWorkshops/dayinthelife-integration#200]
Eliminate cumbersome user assignment process and issues with accessing workshop links from Google Docs for some users.

**Comment by sigreen** [comment]
Tried this out during Columbus OH workshop and was successful.  The procedure was as follows:

(1) Walkthrough citizen-integrator track lab01 with the group
(2) Write on whiteboard bit.ly link to instructions here: https://github.com/RedHatWorkshops/dayinthelife-integration
(3) Verbally assign usernames to each participant and have them write on survey form
(4) Write on whiteboard the environment password
