### ISSUE TITLE
[Integreatly] Integreatly installer needs a cleanup script

### ISSUE THREAD

**Issue by aidenkeating** [RedHatWorkshops/dayinthelife-integration#211]
It would be nice for cases where there are errors (and cases where a user wants to revert to a normal Integreatly cluster) if there was an integreatly_uninstall playbook. This would simply undo any changes made by the DIL installer

* Remove Gogs
* Remove Microcks
* Remove DIL realms from SSO
* Remove tenants from 3scale
* Remove 3scale routes for DIL (2 per user)
* Remove APICurio
* Remove custom stack from Che

**Comment by sedroche** [comment]
Taking on on this task.

**Comment by mhockelberg** [comment]
@sedroche having this clean uninstall will become important soon as all DIL workshops being run in the field will be expected to be provisioned via RHPDS as of March 2019 per Integreatly team.

**Comment by sedroche** [comment]
Hi @mhockelberg 
This issue should have been closed as part of https://github.com/RedHatWorkshops/dayinthelife-integration/pull/229, apologies for that.

https://github.com/RedHatWorkshops/dayinthelife-integration/pull/229 added an uninstall playbook which removes any DIL parts (outlined in this issue description) from an integreatly cluster which has it's [own uninstall script for the services provisioned by that script](https://github.com/integr8ly/installation/blob/master/evals/playbooks/uninstall.yml).

So to clear an RHPDS cluster with integreatly + DIl you would run both uninstall scripts.

Does that answer your question?

**Comment by mhockelberg** [comment]
Hi @sedroche yes, thank you.

**Comment by honghuac** [comment]
Issue addressed in #229
