### ISSUE TITLE
[Integreatly] Make Gogs role idempotent

### ISSUE THREAD

**Issue by aidenkeating** [RedHatWorkshops/dayinthelife-integration#212]
Currently the Gogs role is not idempotent. This causes issues when an error occurs while running the playbook as the project needs to be removed before running the playbook again. It would be good to make the Gogs role idempotent. The main sections here are creating a user and creating repos. We need to continue if they already exist.

**Comment by weimeilin79** [comment]
@aidenkeating we are editing content inside the Gog repos. Would that be better if we remove the accounts when we clean up.

**Comment by odra** [comment]
I am going to work on this issue.
