### ISSUE TITLE
Unable to run integreatly install in ODS

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#215]
I ran ansible-playbook-2.7 -i inventory/integreatly.inventory playbooks/openshift/integreatly.yml on bastin server, but it failed during the sso setup. 

fatal: [master.dilsa-d0fa.openshiftworkshop.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'master.dilsa-d0fa.openshiftworkshop.com' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n", "unreachable": true}''

@aidenkeating

**Comment by mhockelberg** [comment]
@weimeilin79 What is the fix for this issue?  I just hit it trying to run this install.  Thanks.

**Comment by hguerrero** [comment]
@mhockelberg see #218
