### ISSUE TITLE
Missing instructions on how to install on RHPDS-provisioned integr8ly

### ISSUE THREAD

**Issue by hguerrero** [RedHatWorkshops/dayinthelife-integration#218]
There are no instructions on how to actually install the workshop on RHPDS, is it using the APB? calling the ansible playbooks?

**Comment by odra** [comment]
You would have to ssh into the bastion server and run a couple of commands:

1. ssh into the bastion server
2. switch to root user (sudo -i)
3. clone the installer repo
4. get the master node url (oc get nodes | grep master)
5. edit the inventory (`support/install/ansible/inventory/integreatly.inventory`) file and change the master node url from 127.0.0.1 to the master node addr
6. replace "dayinlife" by your cluster guid for both `ocp_domain` and `ocp_apps_domain` properties 
7. cd into `support/install/ansible` and run the integreatly playbook (`ansible-playbook -i inventory/inventory/integreatly.inventory playbooks/openshift/integreatly.yml`)

**Comment by hguerrero** [comment]
Please add those to https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/docs/install.md

or create new file.
