### ISSUE TITLE
Lab 7/Step1.5 clearer instructions and image

### ISSUE THREAD

**Issue by clarkngo** [RedHatWorkshops/dayinthelife-integration#249]
Typo:
On the **right** menu select Home Page, and replace the entire content with what's in the example link example

It should be:
On the **left** menu select Home Page, and replace the entire content with what's in the example link example

Also, proposing a clear image instruction on what content to replace.
![15-homepage-devportal](https://user-images.githubusercontent.com/30854108/51367133-04407980-1a9e-11e9-93e8-14f43a95f3c5.png)

**Comment by VinayBhalerao** [comment]
Closing via https://github.com/RedHatWorkshops/dayinthelife-integration/pull/250

@clarkngo 🏅
