### ISSUE TITLE
Lab 6/Step2 - Common gotcha

### ISSUE THREAD

**Issue by clarkngo** [RedHatWorkshops/dayinthelife-integration#251]
When running this command:
```curl -X POST http://threescale-automate-international.dil.opentry.me/threescale/automate/{YOUR_API_TOKEN}/{USERX}/{OPENSHIFT_APP_URL}```
If user encountered error:
`org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking https://{USERX}-admin.dil1.opentry.me/admin/api/services.xml with statusCode: 422`

<img width="1157" alt="screen shot 2019-01-17 at 9 31 46 pm" src="https://user-images.githubusercontent.com/30854108/51367438-7796bb00-1a9f-11e9-87a8-1e0acd7969ee.png">

This may be due to a failed build. Troubleshoot by deleting SSO Location API.
SSO Location API can be located here:

1. In your browser, `https://{USERX}-admin.dil1.opentry.me/config/services`
2. In the tab menu, click **APIs**
3. Click SSO Location API - **Definition**
4. Click **edit**
5. Click **I understand the consequences, proceed to delete 'SSO Location API' service.**

![image](https://user-images.githubusercontent.com/30854108/51367692-a95c5180-1aa0-11e9-90c9-2a1f3026b168.png)

Try running this command again in the terminal:
```curl -X POST http://threescale-automate-international.dil.opentry.me/threescale/automate/{YOUR_API_TOKEN}/{USERX}/{OPENSHIFT_APP_URL}```

**Comment by VinayBhalerao** [comment]
Closing via https://github.com/RedHatWorkshops/dayinthelife-integration/pull/252/files
