### ISSUE TITLE
[RHPDS] - Eclipse che is slow

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#268]
I was trying the run the lab 3 of developer track for Eclipse che, and found considerably slow.
- time to load the IDE
- Run the spring:boot
- Run the frabic8

We should test with a certain number of users and compare the performance of rhpds vs what integreately provided us earlier.

**Comment by mhockelberg** [comment]
@VinayBhalerao @hguerrero took over 5 minutes to create a Che workspace this morning on RHPDS V2 install.

**Comment by VinayBhalerao** [comment]
We can close this. The team completed 2 workshops on rhpds and it looks good.
