### ISSUE TITLE
V2 - Developer Track - Lab 1 API Design - Updates Needed

### ISSUE THREAD

**Issue by mhockelberg** [RedHatWorkshops/dayinthelife-integration#272]
Overview

	Solution Explorer URL needs to be modified to be described in a way that supports RHPDS and other domains.
	
Step 1: Importing APIs with Apicurio Studio

	Task 1 - Instruction should be navigate to Solution Explorer and launch to OCP console.

**Comment by vap0rtranz** [comment]
@mhockelberg You mean the URL that looks like: https://tutorial-web-app-webapp.apps.<UNIQUE_SUBDOMAIN>.openshiftworkshop.com?

That's probably difficult in standardized docs b/c it will be unique each time.  As "Instructors" of the Lab, look for the correct URL in email from RHPDS.  Something like:

```
Web App URL: https://tutorial-web-app-webapp.apps.dil-testing-0345.openshiftworkshop.com
```

**Comment by honghuac** [comment]
Addressed and closed.
