### ISSUE TITLE
V2 - Developer Track - Lab 6 Managed API Endpoints - Updates Needed

### ISSUE THREAD

**Issue by mhockelberg** [RedHatWorkshops/dayinthelife-integration#277]
All screen captures for 3scale need to be updated in this lab to match with UI enhancements/changes.  Instructions for all of the tasks need to reflect the new navigation.

Overview

	Solution Explorer URL needs to be modified to be described in a way that supports RHPDS and other domains.
	
	International application URL needs to be modified to be described in a way that supports RHPDS and other domains OR add it to the Solution Explorer application links.
	
Step 1: Get API Token for Automation

	Task 1 - 3scale Admin Portal URL needs to be modified to be described in a way that supports RHPDS and other domains.  This part of the instruction should be navigate to Solution Explorer and launch to 3scale Admin Portal.
	
	Task 7 - Add "Click Create Access token" to end of instructions.
	
Step 2: Start managing your APIs

	Automation URL (used in curl command) needs to be modified to be described in a way that supports RHPDS and other domains.  Maybe this can be added to the Solution Explorer during user environment provisioning and displayed for each user to copy?

**Comment by VinayBhalerao** [comment]
assigning to @VinayBhalerao

**Comment by VinayBhalerao** [comment]
Completed both 3scale labs for citizen integrator and developer. Closing.
