### ISSUE TITLE
uninstall script error

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#280]
1. Changed the inventory in `inventories/uninstall.workshop.inventory` for [master]

2. Ran the uninstall script using command `ansible-playbook -i inventories/uninstall.workshop.inventory playbooks/openshift/uninstall.yml`

3. Below error is thrown
```
[root@bastion ansible]# ansible-playbook -i inventories/uninstall.workshop.inventory playbooks/openshift/uninstall.yml
 [WARNING]: A duplicate localhost-like entry was found (localhost). First found
localhost was 127.0.0.1


PLAY [Get master config] ************************************************************

TASK [include_role : master_config] *************************************************
ERROR! the role 'master_config' was not found in /home/dayinthelife-integration-2/support/uninstall/ansible/playbooks/openshift/roles:/etc/ansible/roles:/usr/share/ansible/roles:/home/dayinthelife-integration-2/support/uninstall/ansible/playbooks/openshift

The error appears to have been in '/home/dayinthelife-integration-2/support/uninstall/ansible/playbooks/openshift/uninstall.yml': line 7, column 13, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - include_role:
      name: master_config
            ^ here

	to retry, use: --limit @/home/dayinthelife-integration-2/support/uninstall/ansible/playbooks/openshift/uninstall.retry```

**Comment by aidenkeating** [comment]
@VinayBhalerao This looks to be attempting to access the same `master_config` role used in the installation (It was probably assuming the installation and uninstallation shared roles).

This is where the `master_config` role is currently stored https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/support/install/ansible/playbooks/openshift/roles

You could symlink the directory to the uninstaller roles to (https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/support/uninstall/ansible/playbooks/openshift/roles), or just copy it over.

**Comment by VinayBhalerao** [comment]
@aidenkeating Thanks for the suggestion. It helped!

The problem that I see now is even if the cluster is provisioned for 5 users, the script tries to uninstall in loop for all 50 users.

We need to check why it loops over 50 users even if 5 users are provisioned.

**Comment by VinayBhalerao** [comment]
Added here https://github.com/RedHatWorkshops/dayinthelife-integration/blob/V2/support/uninstall/RHPDS-uninstallation.md

**Comment by aidenkeating** [comment]
@VinayBhalerao 50 users seems to be hardcoded here (https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/uninstall/ansible/playbooks/openshift/uninstall.yml#L27).

It'd probably be best to:
* Remove that line.
* Add a default `usersno` value to the `uninstall-workshop` role defaults (Whatever the default amount of provisioned users are).
* When needed, override the `usersno` val when running the playbook. Like `ansible-playbook -i myinventory uninstall.yml -e usersno=5` or using a var in the inventory you provide.
