### ISSUE TITLE
Install script error with backend services

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#281]
When running the ansible script on RHPDS, the backend location db + services are not created in the UserX Project.  Here is the Ansible role I'm talking about: https://github.com/RedHatWorkshops/dayinthelife-integration/blob/9d35b7ca55bd77f626a85e33e1936c6504aa5c8f/support/install/ansible/playbooks/openshift/roles/provision_backend/tasks/main.yml#L32 . If I run the oc new-app command on Bastion directly it creates the service, but during the full playbook install it is skipping over the backend services for some reason.  Any thoughts?

**Comment by aidenkeating** [comment]
@sigreen Do you have the logs from the ansible run and the command you ran? If Ansible is skipping that task it could be because `configure_only` is set to `true` somewhere (maybe the inventory used).

**Comment by sigreen** [comment]
@aidenkeating Here is the ansible log output and my inventory file that I updated.  I already had a running instance and ran the uninstall script that @VinayBhalerao was working on to tear down the DIL stuff.  I reran the V2 install script and doesn't appear to have worked.  I'm thinking I might just reprovision another RHPDS instance and try fresh. Otherwise, `configure_only` is set to `false` at least in my inventory file.

[output.txt](https://github.com/RedHatWorkshops/dayinthelife-integration/files/2919806/output.txt)

[integreatly.inventory.txt](https://github.com/RedHatWorkshops/dayinthelife-integration/files/2919812/integreatly.inventory.txt)

**Comment by VinayBhalerao** [comment]
I do not see the apps in `default` project whereas the same are created in `international`

**default project**
```
 oc project default
Now using project "default" on server "https://master.san-francisco-e07f.openshiftworkshop.com:443".

oc get pods
NAME                          READY     STATUS    RESTARTS   AGE
docker-registry-1-9psx6       1/1       Running   0          3d
logging-eventrouter-1-th75g   1/1       Running   0          3d
registry-console-1-bq5f6      1/1       Running   0          3d
router-2-xtq75                1/1       Running   0          3d
```

**international project**
```
oc project international
Now using project "international" on server "https://master.san-francisco-e07f.openshiftworkshop.com:443".

oc get pods
NAME                          READY     STATUS      RESTARTS   AGE
location-service-1-72ddh      1/1       Running     0          1d
location-service-1-build      0/1       Completed   0          1d
location-soap-1-build         0/1       Completed   0          1d
location-soap-1-fn6n4         1/1       Running     0          1d
location-soap2rest-1-build    0/1       Completed   0          1d
location-soap2rest-1-hdq2w    1/1       Running     0          1d
postgresql-1-g7pqx            1/1       Running     0          1d
threescale-automate-1-build   0/1       Completed   0          1d
threescale-automate-1-vmpt7   1/1       Running     0          1d
www-1-build                   0/1       Completed   0          1d
www-1-qtl96                   1/1       Running     0          1d
```

**Comment by VinayBhalerao** [comment]
btw in installation instructions we do set `configure_only` to `true` https://github.com/RedHatWorkshops/dayinthelife-integration/blob/V2/support/install/ansible/inventory/workshop.inventory#L18

**Comment by aidenkeating** [comment]
@sigreen That Ansible log indicates that the installation failed at provisioning Gogs, which from what I understand is before those backend services are provisioned

**Comment by sigreen** [comment]
Thanks @aidenkeating and @VinayBhalerao .  I have logged #285 to address the related gogs provisioning issue

**Comment by sigreen** [comment]
I have fixed the gogs issue, and the script progresses somewhat. But the backend services are still not created.  My new error is related to apicurio installation:

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc new-app -f https://gist.githubusercontent.com/aidenkeating/e14b8150118c6fc2d446ad2644a38d97/raw/2fe99d4b91e7c2d424fc413ca348383a4a378a5b/apicurio-template.yml -p UI_ROUTE=apicurio-studio.apps.optum-ed0e.openshiftworkshop.com -p API_ROUTE=apicurio-studio-api.apps.optum-ed0e.openshiftworkshop.com -p WS_ROUTE=apicurio-studio-ws.apps.optum-ed0e.openshiftworkshop.com -p AUTH_ROUTE=sso-sso.apps.optum-ed0e.openshiftworkshop.com -p API_STUDIO_API_IMAGE_TAG=0.2.17.Final -p API_STUDIO_WS_IMAGE_TAG=0.2.17.Final -p API_STUDIO_UI_IMAGE_TAG=0.2.17.Final -n apicurio", "delta": "0:00:01.648772", "end": "2019-03-04 18:36:19.687469", "msg": "non-zero return code", "rc": 1, "start": "2019-03-04 18:36:18.038697", "stderr": "    error: imagestreams.image.openshift.io \"api\" already exists\n    error: imagestreams.image.openshift.io \"ws\" already exists\n    error: imagestreams.image.openshift.io \"ui\" already exists\n    error: persistentvolumeclaims \"postgresql-data\" already exists\n    error: secrets \"postgresql\" already exists\n    error: services \"postgresql\" already exists\n    error: services \"apicurio-studio-api\" already exists\n    error: services \"apicurio-studio-ws\" already exists\n    error: services \"apicurio-studio-ui\" already exists\n    error: deploymentconfigs.apps.openshift.io \"postgresql\" already exists\n    error: deploymentconfigs.apps.openshift.io \"apicurio-studio-api\" already exists\n    error: deploymentconfigs.apps.openshift.io \"apicurio-studio-ws\" already exists\n    error: deploymentconfigs.apps.openshift.io \"apicurio-studio-ui\" already exists\n    error: routes.route.openshift.io \"apicurio-studio-api\" already exists\n    error: routes.route.openshift.io \"apicurio-studio-ws\" already exists\n    error: routes.route.openshift.io \"apicurio-studio-ui\" already exists", "stderr_lines": ["    error: imagestreams.image.openshift.io \"api\" already exists", "    error: imagestreams.image.openshift.io \"ws\" already exists", "    error: imagestreams.image.openshift.io \"ui\" already exists", "    error: persistentvolumeclaims \"postgresql-data\" already exists", "    error: secrets \"postgresql\" already exists", "    error: services \"postgresql\" already exists", "    error: services \"apicurio-studio-api\" already exists", "    error: services \"apicurio-studio-ws\" already exists", "    error: services \"apicurio-studio-ui\" already exists", "    error: deploymentconfigs.apps.openshift.io \"postgresql\" already exists", "    error: deploymentconfigs.apps.openshift.io \"apicurio-studio-api\" already exists", "    error: deploymentconfigs.apps.openshift.io \"apicurio-studio-ws\" already exists", "    error: deploymentconfigs.apps.openshift.io \"apicurio-studio-ui\" already exists", "    error: routes.route.openshift.io \"apicurio-studio-api\" already exists", "    error: routes.route.openshift.io \"apicurio-studio-ws\" already exists", "    error: routes.route.openshift.io \"apicurio-studio-ui\" already exists"], "stdout": "--> Deploying template \"apicurio/apicurio-studio\" for \"https://gist.githubusercontent.com/aidenkeating/e14b8150118c6fc2d446ad2644a38d97/raw/2fe99d4b91e7c2d424fc413ca348383a4a378a5b/apicurio-template.yml\" to project apicurio\n\n     apicurio-studio\n     ---------\n     Congratulations on deploying Apicurio Studio into OpenShift!\n     \n     The following secret(s) have been created in your project:\n     \n            SQL Username: userFQA\n            SQL Password: 77d6rgrsJtgwJ7i3\n            SQL Connection URL: postgresql://postgresql:5432/\n     \n     All Apicurio components have been deployed and configured.  Please note\n     that the authentication component (Keycloak) requires additional configuration\n     for it to support all Apicurio functionality (specifically account linking).\n     In addition, you may want to configure Keycloak to your particular taste (for\n     example you may want to enable social logins).\n\n     * With parameters:\n        * User Interface Route Name=apicurio-studio.apps.optum-ed0e.openshiftworkshop.com\n        * API Route Name=apicurio-studio-api.apps.optum-ed0e.openshiftworkshop.com\n        * Editing Route Name=apicurio-studio-ws.apps.optum-ed0e.openshiftworkshop.com\n        * Authentication Route Name=sso-sso.apps.optum-ed0e.openshiftworkshop.com\n        * PostgreSQL Connection Username=userFQA # generated\n        * PostgreSQL Connection Password=77d6rgrsJtgwJ7i3 # generated\n        * Database Name=apicuriodb\n        * Keycloak Realm=apicurio\n        * Keycloak Admin Username=adminPBW # generated\n        * Keycloak Admin Password=Cwhf1jQyvdCW8uhC # generated\n        * UI Min JVM Memory Limit=512m\n        * UI Max JVM Memory Limit=2048m\n        * UI Max Memory Limit=4Gi\n        * UI Memory Request=700Mi\n        * UI Max CPU Limit=1\n        * UI CPU Request=100m\n        * API Min JVM Memory Limit=512m\n        * API Max JVM Memory Limit=4096m\n        * API Max Memory Limit=6Gi\n        * API Memory Request=800Mi\n        * API Max CPU Limit=1\n        * API CPU Request=100m\n        * WS Min JVM Memory Limit=512m\n        * WS Max JVM Memory Limit=4096m\n        * WS Max Memory Limit=6Gi\n        * WS Memory Request=900Mi\n        * WS Max CPU Limit=1\n        * WS CPU Request=100m\n        * AUTH Max Memory Limit=1300Mi\n        * AUTH Memory Request=600Mi\n        * AUTH Max CPU Limit=1\n        * AUTH CPU Request=100m\n        * API_STUDIO_API_IMAGE_TAG=0.2.17.Final\n        * API_STUDIO_WS_IMAGE_TAG=0.2.17.Final\n        * API_STUDIO_UI_IMAGE_TAG=0.2.17.Final\n\n--> Creating resources ...\n--> Failed", "stdout_lines": ["--> Deploying template \"apicurio/apicurio-studio\" for \"https://gist.githubusercontent.com/aidenkeating/e14b8150118c6fc2d446ad2644a38d97/raw/2fe99d4b91e7c2d424fc413ca348383a4a378a5b/apicurio-template.yml\" to project apicurio", "", "     apicurio-studio", "     ---------", "     Congratulations on deploying Apicurio Studio into OpenShift!", "     ", "     The following secret(s) have been created in your project:", "     ", "            SQL Username: userFQA", "            SQL Password: 77d6rgrsJtgwJ7i3", "            SQL Connection URL: postgresql://postgresql:5432/", "     ", "     All Apicurio components have been deployed and configured.  Please note", "     that the authentication component (Keycloak) requires additional configuration", "     for it to support all Apicurio functionality (specifically account linking).", "     In addition, you may want to configure Keycloak to your particular taste (for", "     example you may want to enable social logins).", "", "     * With parameters:", "        * User Interface Route Name=apicurio-studio.apps.optum-ed0e.openshiftworkshop.com", "        * API Route Name=apicurio-studio-api.apps.optum-ed0e.openshiftworkshop.com", "        * Editing Route Name=apicurio-studio-ws.apps.optum-ed0e.openshiftworkshop.com", "        * Authentication Route Name=sso-sso.apps.optum-ed0e.openshiftworkshop.com", "        * PostgreSQL Connection Username=userFQA # generated", "        * PostgreSQL Connection Password=77d6rgrsJtgwJ7i3 # generated", "        * Database Name=apicuriodb", "        * Keycloak Realm=apicurio", "        * Keycloak Admin Username=adminPBW # generated", "        * Keycloak Admin Password=Cwhf1jQyvdCW8uhC # generated", "        * UI Min JVM Memory Limit=512m", "        * UI Max JVM Memory Limit=2048m", "        * UI Max Memory Limit=4Gi", "        * UI Memory Request=700Mi", "        * UI Max CPU Limit=1", "        * UI CPU Request=100m", "        * API Min JVM Memory Limit=512m", "        * API Max JVM Memory Limit=4096m", "        * API Max Memory Limit=6Gi", "        * API Memory Request=800Mi", "        * API Max CPU Limit=1", "        * API CPU Request=100m", "        * WS Min JVM Memory Limit=512m", "        * WS Max JVM Memory Limit=4096m", "        * WS Max Memory Limit=6Gi", "        * WS Memory Request=900Mi", "        * WS Max CPU Limit=1", "        * WS CPU Request=100m", "        * AUTH Max Memory Limit=1300Mi", "        * AUTH Memory Request=600Mi", "        * AUTH Max CPU Limit=1", "        * AUTH CPU Request=100m", "        * API_STUDIO_API_IMAGE_TAG=0.2.17.Final", "        * API_STUDIO_WS_IMAGE_TAG=0.2.17.Final", "        * API_STUDIO_UI_IMAGE_TAG=0.2.17.Final", "", "--> Creating resources ...", "--> Failed"]}
`

**Comment by aidenkeating** [comment]
@sigreen Sounds the like `apicurio` namespace is already there and the role isn't idempotent. Adding something like:

```
register: apicurio_create
failed_when: apicurio_create.stderr != '' and 'already exists' not in apicurio_create.stderr
```

to [that provisioning task](https://github.com/RedHatWorkshops/dayinthelife-integration/blob/V2/support/install/ansible/playbooks/openshift/roles/provision_apicurio/tasks/main.yml#L9) might be the best option

**Comment by sigreen** [comment]
Fixed.  All backend projects are now installed in a single `international` workspace are implementing idempotency.
