### ISSUE TITLE
V2 - Developer Track - Lab 2 API Mocking - link broken

### ISSUE THREAD

**Issue by mhockelberg** [RedHatWorkshops/dayinthelife-integration#282]
"Skipping The Lab" link returns 404.

**Comment by mhockelberg** [comment]
![image](https://user-images.githubusercontent.com/686612/53647803-4cf66100-3c0c-11e9-8e31-44d978a8ae51.png)

**Comment by VinayBhalerao** [comment]
The link is `http://location-service-international.apps.san-francisco-e07f.openshiftworkshop.com/locations` (it might 404 after the cluster is down. I have verified now that it returns json array for locations)

After https://github.com/RedHatWorkshops/dayinthelife-integration/issues/284 is fixed, we can then change the link to `http://location-service-international.{openshift-app-host}/locations` in the adoc
