### ISSUE TITLE
{openshift-app-host} is not set

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#284]
In both labs, we have {openshift-app-host} but I do not see that set somewhere in the code...

For now, all the instructions looks like this
![red_hat_solution_explorer](https://user-images.githubusercontent.com/7827135/53671095-c9e80180-3c31-11e9-8786-117b784a4fd8.png)

@evanshortiss can you have a look at it?

**Comment by jasonmadigan** [comment]
@aidenkeating ^

**Comment by jasonmadigan** [comment]
If we can get a link showcasing the bug, this should be fairly straightforward to debug/fix

**Comment by VinayBhalerao** [comment]
URL: https://tutorial-web-app-webapp.apps.san-francisco-e07f.openshiftworkshop.com/tutorial/dayinthelife-integration.git-developer-track-lab01/task/1

Scroll down to section `Environment`

**Comment by jasonmadigan** [comment]
@VinayBhalerao cool, will try with `evals50`

**Comment by aidenkeating** [comment]
@VinayBhalerao Can you try adding the `[subs="attributes+"]` attribute to the block, so it'd be like:

```
[source,bash,subs="attributes+"]
----
https://tutorial-web-app-webapp.{openshift-app-host}
----
```

this should include the attributes in the source block.

**Comment by VinayBhalerao** [comment]
@aidenkeating That helped! thanks.
