### ISSUE TITLE
Integrator Lab 2 copied URL is incorrect

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#287]
For the online CURL command, the copied URL appears as:

 http://microcks.apps.optum-ed0e.openshiftworkshop.com/rest/Locations-user2/1.0.0/locations

The `user2` parameter should be `User2` so that the URL is valid

**Comment by VinayBhalerao** [comment]
I guess we need to update instructions and screenshots to match `user2` because the values are injected using `{user-username}` === user2...

**Comment by sigreen** [comment]
Retested.  This problem is now resolved
