### ISSUE TITLE
SSH to bastion server fails

### ISSUE THREAD

**Issue by torbjorndahlen** [RedHatWorkshops/dayinthelife-integration#297]
SSH to bastion fails: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)
When using the certificate provided from https://www.opentlc.com/keys/ocp-workshop.pem

**Comment by torbjorndahlen** [comment]
Ok, you actually need to SSH as ec2-user. This should have been stated in the instructions (https://github.com/RedHatWorkshops/dayinthelife-integration/blob/V2/support/install/RHPDSInstallation.md), so maybe update this document with SSH details?

**Comment by vap0rtranz** [comment]
> Ok, you actually need to SSH as ec2-user.

@torbjorndahlen This is standard procedure for RHPDS buildouts on AWS.  There is a private Mojo on it but not open to the public.

Suggest /closed

**Comment by sigreen** [comment]
Closed as per suggestion from @vap0rtranz
