### ISSUE TITLE
Unclear instruction at RHPDSInstallation.md

### ISSUE THREAD

**Issue by torbjorndahlen** [RedHatWorkshops/dayinthelife-integration#298]
In the https://github.com/RedHatWorkshops/dayinthelife-integration/blob/V2/support/install/RHPDSInstallation.md 
instructions step 5 is says: "Change the master host in the inventory file (support/install/ansible/inventory/integreatly.inventory) to use the internal master node hostname retrieved in the previous step;"
For improved clarity the directory should be dayinthelife-integration/support/install/ansible/inventory/integreatly.inventory

**Comment by sigreen** [comment]
Fixed by updating the RHPDS installation procedure.
