### ISSUE TITLE
Task setup_che_multi fails

### ISSUE THREAD

**Issue by torbjorndahlen** [RedHatWorkshops/dayinthelife-integration#300]
When running ansible-playbook -i inventory/integreatly.inventory playbooks/openshift/integreatly.yml
the following error occurs:

TASK [setup_che_multi : set_fact] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'access_token'\n\nThe error appears to have been in '/root/dayinthelife-integration/support/install/ansible/playbooks/openshift/roles/setup_che_multi/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact: TKN={{ (token_text.stdout | from_json).access_token }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

**Comment by VinayBhalerao** [comment]
@torbjorndahlen Which repo did you use to deploy? `master` or `V2`?

**Comment by torbjorndahlen** [comment]
I used V2

git clone https://github.com/RedHatWorkshops/dayinthelife-integration.git -b V2;

**Comment by sigreen** [comment]
Unable to reproduce this issue now that all scripts have been migrated from V2 to Master.
