### ISSUE TITLE
Link to Red Hat Solution Explorer does not work

### ISSUE THREAD

**Issue by torbjorndahlen** [RedHatWorkshops/dayinthelife-integration#301]
When following the lab steps in 
https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/docs/labs/citizen-integrator-track/lab01#lab-1

The link https://tutorial-web-app-webapp.dil.opentry.me

Is not working and there are no instructions how to proceed from here.

**Comment by sigreen** [comment]
Markdown docs have been deleted and migrated to asciidocs.  This issue was resolved with the migration of V2 to Master
