### ISSUE TITLE
Developer track: Apicuro UI updated? or SSO not working??

### ISSUE THREAD

**Issue by vap0rtranz** [RedHatWorkshops/dayinthelife-integration#306]
The Apicuro UI looks different that what's documented [in Lab1](https://github.com/RedHatWorkshops/dayinthelife-integration/tree/V2/docs/labs/developer-track/lab01#lab-1)

Here is what I'm seeing after logging in as user evals01 -- note there is no username in the upper right:

![apciuro-ui](https://user-images.githubusercontent.com/11527819/54869784-833a8280-4d6b-11e9-9a3a-5c6e2836e096.png)

Here is what the Solution Explorer looks like after logging in as user evals01 -- note the username is listed in the upper right:

![solution-explorer](https://user-images.githubusercontent.com/11527819/54869804-cd236880-4d6b-11e9-8da3-88b62d7f2473.png)

**Comment by sigreen** [comment]
The DIL project has been updated to V2 and the Apicurio version has been updated.  This issue has been resolved when following the walkthrough asciidocs which are published to the tutorial webapp.
