### ISSUE TITLE
Dead link to image 00-open-workspace.png in developer-track lab 03

### ISSUE THREAD

**Issue by apupier** [RedHatWorkshops/dayinthelife-integration#308]
https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/docs/labs/developer-track/lab03#step-1-create-an-eclipse-che-environment-for-your-personal-use

![image](https://user-images.githubusercontent.com/1105127/55137906-7aaec700-5132-11e9-9db0-8adfe17fb4a3.png)

**Comment by VinayBhalerao** [comment]
@apupier we use only adoc https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/docs/labs/developer-track/lab03/walkthrough.adoc and all updates are done there. We use the same adoc for integreatly walkthrough. If you see the issue in walkthroughs, please let us know.

Closing.

**Comment by apupier** [comment]
what about deleting the unused readme?
