### ISSUE TITLE
Lab3 - Unable to establish postgresql connection when running spring boot

### ISSUE THREAD

**Issue by anusuyakuna** [RedHatWorkshops/dayinthelife-integration#312]
The postgresql.service.name property is incorrect in instructions. Please go to Openshift , navigate to Applications and select services. select the database service added and  look at the host name and add the same in Code ready work application properties.

![Hostname](https://user-images.githubusercontent.com/49919950/56604625-07309600-65c8-11e9-8aa8-8e7b0d596bbd.png)

**Comment by VinayBhalerao** [comment]
cc @sigreen 

Need to check the codebase and see why the hostname is different from the instructions `postgresql.user53.svc`

Few users had `postgresql.user53.svc` while others had `postgresql.user53-dayinthe-1313.svc`

**Comment by sigreen** [comment]
Discussed this issue.  It was user issue.  The user updated the incorrect OCP project. Closing as per instructions from @weimeilin79 and @VinayBhalerao
