### ISSUE TITLE
Lab3 - HTTP post  CURL command is incorrect

### ISSUE THREAD

**Issue by anusuyakuna** [RedHatWorkshops/dayinthelife-integration#313]
We need to replace the API URL which works with HTTP GET request in the CURL command for HTTP POST to successfully insert record in database

Example:

 curl --header "Content-Type: application/json" --request POST --data '{"id": 101,"name": "Kakadu","type": "HQ","status": "1","location": {"lat": "78.88436","lng": "99.05295"}}' http://location-service-user53-dayinthe-a3a3.apps.minneapolis-7d38.openshiftworkshop.com/locations

**Comment by VinayBhalerao** [comment]
The URL looks good to me. Tested this on another environment.

Maybe in your case, you were in a different namespace so the URL changed. Closing for now.
