### ISSUE TITLE
Remove patching for webapp and webapp operator

### ISSUE THREAD

**Issue by mhockelberg** [RedHatWorkshops/dayinthelife-integration#316]
Update 
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/setup_webapp/tasks/main.yml 

To remove the 2 commands below.  We should be able to now use the webapp and webapp operator versions being deployed with Integreatly (v 1.3 or 1.4) on RHPDS.  If someone can verify that this change is okay, I'll make it and close this issue.

- name: Change webapp container image #use v2.6.0
  shell: oc patch dc tutorial-web-app --patch='{"spec":{"template":{"spec":{"containers":[{"name":"tutorial-web-app","image":"quay.io/integreatly/tutorial-web-app:v2.6.0"}]}}}}' -n {{ configmap_namespace }}

- name: Change webapp operator container image #use Aiden's patch v0.0.8
  shell: oc patch deployment tutorial-web-app-operator --patch='{"spec":{"template":{"spec":{"containers":[{"name":"tutorial-web-app-operator","image":"quay.io/integreatly/tutorial-web-app-operator:v0.0.8"}]}}}}' -n {{ configmap_namespace }}

**Comment by mhockelberg** [comment]
@aidenkeating should I go ahead and make/commit this change?

**Comment by hodrigohamalho** [comment]
As it is blocking I think it should be merged asap.

**Comment by mhockelberg** [comment]
Removed patch operations that were no longer needed and were causing issues with Integreatly 1.4.
