### ISSUE TITLE
provision-threescale playbook fails on task Get Id client www-secured

### ISSUE THREAD

**Issue by mikeintoch** [RedHatWorkshops/dayinthelife-integration#317]
When the environment is provisioning the task on [provision-thresscale] Get id cliente www-secured fails.

I am using rhpds environmente OCP: 4.11.43 and Integreatly v4.0

**Comment by VinayBhalerao** [comment]
@mikeintoch Please use OCP 3.11.14 and integreatly 1.3.0 while provisioning the environment of RHPDS

**Comment by mandibuswell** [comment]
It seems that only OCP 3.11.43 is available from the drop down menu even
when selecting v1.3 of Integreatly.
Provisions via RHPDS seem to be hanging at the moment, I am unable to get
any through successfully either.

**Comment by mandibuswell** [comment]
I also get this this is the third time I have run the playbook and I am
using 1.3 and OCP 3.11.43 (the only choice for OCP)

TASK [provision_threescale : Get id for client 'www-secured']
******************
FAILED - RETRYING: Get id for client 'www-secured' (20 retries left).

**Comment by mhockelberg** [comment]
This is due to RHPDS provisioning with self-signed certs.  The Zync component is not configured to work with self-signed certs so when the 3scale application is created (client ID = www-secured) the Zync sync to RH SSO to create the www-secured client is failing.  This should be resolved once RHPDS starts provisioning with CA certs again, hopefully early this week.

**Comment by mandibuswell** [comment]
Is there a work around? Thanks.

**Comment by mandibuswell** [comment]
Thanks. So this also explains why the zync of the client id that you do in
Lab 7 step 2.4 where you select the Client ID for the client that you set
up in Lab 4 API Security Step 3.11 doesn't show up.
Note the lab notes say:
*If you do not find the CLIENT_ID, make sure you correctly executed the
sync between 3scale and RHSSO in Lab 4, Task 3.11. You should also check
Step 1.4 in this lab to ensure that the SSO_URL correctly begins with
`https://`*


*Is there a workaround for this?*

**Comment by mhockelberg** [comment]
RHPDS started provisioning with CA certs this morning.  This issue should be resolved on RHPDS Integreatly/DIL workshop envs that were/are provisioned after 11 AM Eastern US today.

**Comment by mandibuswell** [comment]
I am going to reprovision the lab, however in the meantime I did find a
sort of workaround for the zync issues that at least got me through to the
end of integrator lab 6 which is to manually provision the client id in
both cases ie for www-secured and in lab 6 where you need the apiuser
client id.

I will try with a fresh lab as well.

**Comment by mhockelberg** [comment]
I am going to close this issue, unless there are additional questions?

**Comment by mikeintoch** [comment]
It works again... Thanks for your support
