### ISSUE TITLE
RHPDS Steps 5 and 6 Need More Detail

### ISSUE THREAD

**Issue by mmistretta** [RedHatWorkshops/dayinthelife-integration#323]
5. Update inventory files with URLs from previous step. Change to local git directory: cd dayinthelife-integration/support/install/ansible/inventory/
 
---> the from previous step does not print off the host, an echo is needed to see it

6. Replace the internal master node hostname retrieved in the previous step in integreatly.inventory;

--> unclear what to replace for newbies

**Comment by honghuac** [comment]
Addessed with this commit: https://github.com/RedHatWorkshops/dayinthelife-integration/commit/deebf8eab5d9b0b667b22e2ea6f382c907d3acb8#diff-deedc872391b096ad48ecaa49f9c5faaL111
