### ISSUE TITLE
Playbook failed in TASK [provision_threescale : Get id for client 'www-secured'] 

### ISSUE THREAD

**Issue by mikeintoch** [RedHatWorkshops/dayinthelife-integration#332]
The playbook is failed when try to deploy Integreatly is using the version 1.4.1 and OCP 3.11.43.

**Comment by mikeintoch** [comment]
This is due to RHPDS provisioning with self-signed certs. The Zync component is not configured to work with self-signed certs so when the 3scale application is created (client ID = www-secured) the Zync sync to RH SSO to create the www-secured client is failing. This should be resolved once RHPDS starts provisioning with CA certs again, hopefully early this week.

Do you know a workaround?

**Comment by honghuac** [comment]
Those versions of Integreatly and OCP worked for me, numerous times. There have been some unstability recently though, on RHPDS. Please try again.
