### ISSUE TITLE
Missing walkthroughs

### ISSUE THREAD

**Issue by honghuac** [RedHatWorkshops/dayinthelife-integration#344]
My observation regarding Integreatly 1.5, with DIL (of Master branch) installed.
DIL walkthroughs do not appear in the Tutorial Web App, despite successful installation.
Should the V2 branch be officially used and tested?

**Comment by hguerrero** [comment]
Is it just a single issue or two? Better to split them to do a better follow up. 

Re: both users that was possible since the first version.

**Comment by honghuac** [comment]
Probable cause of issue lies in this parameter in the CR `webapp`:
`WALKTHROUGH_LOCATIONS: https://github.com/integr8ly/tutorial-web-app-walkthroughs#v1.7.3,https://github.com/aerogear/mobile-walkthrough#0.4.0 path: /home/tutorial-web-app-operator/deploy/template/tutorial-web-app.yml`

**Comment by honghuac** [comment]
Solved.
