### ISSUE TITLE
Failed creating Gogs users

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#355]
`TASK [provision_gogs : Create Gogs users] **************************************************************************************
failed: [localhost] (item=user0) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:37 GMT", "item": "user0", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=5361627072b7bcbe; Path=/; HttpOnly, _csrf=RfQYgtUA_9G3pNHZuM5ezFebDDQ6MTU2OTk5MDIxNzA5ODcwMzQ5Nw%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:37 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user1) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:37 GMT", "item": "user1", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=d05172c434ebbc8e; Path=/; HttpOnly, _csrf=prh1tiBMCT7pee4jLvFHygw0wVM6MTU2OTk5MDIxNzQzMTc5MjMxNw%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:37 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user2) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:37 GMT", "item": "user2", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=2fea5e70a9ddf292; Path=/; HttpOnly, _csrf=qYAVJavRGEpIRL_wUcQx9S1DANc6MTU2OTk5MDIxNzc2MzI4MTEzNQ%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:37 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user3) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:38 GMT", "item": "user3", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=33f6461e378e9ead; Path=/; HttpOnly, _csrf=NrFrgzmrROTlnzWzU8EGmK5h6SY6MTU2OTk5MDIxODA5NDM1MzQxMQ%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:38 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user4) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:38 GMT", "item": "user4", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=b580e4746aa80e17; Path=/; HttpOnly, _csrf=CoO4jz2zJFdubh0BroKeJxZox486MTU2OTk5MDIxODQyNzExNjE5NA%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:38 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user5) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:38 GMT", "item": "user5", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=5d1742d3b6ac25db; Path=/; HttpOnly, _csrf=onrOxBqszGrhiaYMTfpFA1zwHAk6MTU2OTk5MDIxODc1ODEwMjE5MA%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:38 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user6) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:39 GMT", "item": "user6", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=b156446cf2c37c1b; Path=/; HttpOnly, _csrf=1PjEJxsM6sV89gnCD0E1RfRSc9A6MTU2OTk5MDIxOTA4NTM2MzIzMw%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:39 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user7) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:39 GMT", "item": "user7", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=18dd3653415a0201; Path=/; HttpOnly, _csrf=Ks--ViSToRR1VhEYaenQV3izDQU6MTU2OTk5MDIxOTQyMTQzMDYxOQ%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:39 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user8) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:39 GMT", "item": "user8", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=705d7662eefc25d0; Path=/; HttpOnly, _csrf=Rb2m8N-g-GNZ1Oxkt_oa0Xo2ko86MTU2OTk5MDIxOTc1NTM0NzIxNg%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:39 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user9) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:40 GMT", "item": "user9", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=6d61384faecc4e50; Path=/; HttpOnly, _csrf=9lHQaKyAeXvrBywDIc12S_Xd3mI6MTU2OTk5MDIyMDA5NjU5NDE0Mw%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:40 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
failed: [localhost] (item=user10) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Wed, 02 Oct 2019 04:23:40 GMT", "item": "user10", "location": "http://gogs.apps.japan-21b6.open.redhat.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=531b533ffa52856c; Path=/; HttpOnly, _csrf=HihDDBANSrKG21eNmU-PYyxZdts6MTU2OTk5MDIyMDQyNzAwMzU5OQ%3D%3D; Path=/; Expires=Thu, 03 Oct 2019 04:23:40 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=0bbaea26062c67653fcf200d87754b05; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.japan-21b6.open.redhat.com/user/sign_up"}
...ignoring
`

**Comment by honghuac** [comment]
Addressed
