### ISSUE TITLE
[1.5] "Developer Lab 5 - Managed Endpoints, Task 2 of 8" hostname error

### ISSUE THREAD

**Issue by honghuac** [RedHatWorkshops/dayinthelife-integration#356]
**Developer Lab 5 - Managed Endpoints, Task 2 of 8**
This command fails:
`curl -X POST http://threescale-automate-international.apps.demo-56f6.open.redhat.com/threescale/automate/{YOUR_API_TOKEN}/user5/apps.demo-56f6.open.redhat.com`
due to a non-existent hostname - **http://threescale-automate-international.apps.demo-56f6.open.redhat.com**

**Comment by weimeilin79** [comment]
Can you make sure your installation script has install all the parts? mine works

**Comment by honghuac** [comment]
The command works in Integreatly 1.6. Issue closed.
