### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#361]
When logging into the bastion server, the username should be "ec2-user".  I am unable to login with my opentlc username.  This is the command I used instead:

ssh -i ~/.ssh/<your_opentlc_private_key> ec2-user@bastion.GUID.open.redhat.com

**Comment by honghuac** [comment]
I was able to login with my opentlc userid. Anyhow, will add the recommended login strategy as an option.

**Comment by honghuac** [comment]
Also, add this recommend technique in downloading the right Integreatly release archive, to the Integreatly install instructions section: `wget https://github.com/integr8ly/installation/archive/release-1.5.2.zip`

**Comment by honghuac** [comment]
Addressed
