### ISSUE TITLE
Update Environment section for all persona tracks

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#43]
We need to update the Environment lab instructions for all persona tracks with environment login instructions for either Integreatly or RHPDS depending on which envioronment we decide upon.  At the moment, all lab instructions reflect RHPDS.  We need this information AT LEAST 3 business days before the first lab delivery.

**Comment by weimeilin79** [comment]
@yossiko24  We need to have the final decision by end of this week for the November sessions.

**Comment by sigreen** [comment]
Hugo suggested we make a branch for this and start creating the Integreatley

**Comment by sigreen** [comment]
Have updated all labs for all tracks.  Testing in progress
