### ISSUE TITLE
Update Ansible script with latest Apicurio version 02.16.FINAL

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#49]
We have committed to using Apicurio version 02.16.FINAL.  Please update the Ansible script to reflect this.

**Comment by sigreen** [comment]
Looks like we've already shifted to 02.17.FINAL??

**Comment by medberry** [comment]
Concur.

**Comment by sigreen** [comment]
Apicurio 02.17.FINAL verified in production cluster.  Closing issue.
