### ISSUE TITLE
SSO realm not set for Apicurio!

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#66]
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/provision_apicurio/tasks/main.yml

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13 FYI

**Comment by aidenkeating** [comment]
@jasonmadigan I'll be taking this one

**Comment by maleck13** [comment]
Happy with this after aidens update? Should be able to login to the cluster using ```user1 <default password>``` and also into apicuro

**Comment by VinayBhalerao** [comment]
LGTM 👍 . Closing the issue.
