### ISSUE TITLE
International Inc Service are not running

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#67]
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/provision_backend/tasks/main.yml

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13 FYI

**Comment by weimeilin79** [comment]
@aidenkeating Can you please load the new source code from this repo ?  Thanks!

**Comment by weimeilin79** [comment]
@aidenkeating
