### ISSUE TITLE
Custom stack not loaded into Che

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#68]
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/provision_che/tasks/create-ide.yml

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13 FYI

**Comment by sigreen** [comment]
Tested OK on latest cluster (https://integreatly-demo2.opentry.me)
