### ISSUE TITLE
SSO realm not setup for Microcks

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#69]
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/provision_microcks/tasks/main.yml

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13 FYI

**Comment by aidenkeating** [comment]
This is the realm on the latest cluster https://secure-sso-sso.integreatly-demo2.opentry.me/auth/admin/master/console/#/realms/microcks . If someone can confirms it looks correct I'd say we can close this.

**Comment by VinayBhalerao** [comment]
LGTM 👍

**Comment by VinayBhalerao** [comment]
One clarification: the login to account should be `evals01@example.com` or `user1`?

**Comment by maleck13** [comment]
Currently it is user1 as we used what was in the script. However perhaps we can modify that the create evals01@example.com etc they will need to login to microcks separately with that user though.

**Comment by VinayBhalerao** [comment]
Yep, looks good. Closing the issue.
