### ISSUE TITLE
3scale not not multitants

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#70]
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/create-tenants.yml

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13 FYI

**Comment by VinayBhalerao** [comment]
LGTM 👍
