### ISSUE TITLE
3scale Services and plans are not pre-set for Dev track!

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#71]
https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/create-service.yml

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13 FYI

**Comment by maleck13** [comment]
working on this

**Comment by maleck13** [comment]
@weimeilin79 happy with this now?
