### ISSUE TITLE
Unable to open Che - timesout

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#77]
Tried to create a workspace in che using username: evals48@example.com.  Creation timed-out with following message in the logs:

2018-10-22 21:44:56,714[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'evals48@example.com/simon-dev' with id 'workspace45og8pnovmumd34u' created by user 'evals48@example.com'
--
  | 2018-10-22 21:44:59,872[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 330]   - Starting workspace 'evals48@example.com/simon-dev' with id 'workspace45og8pnovmumd34u' by user 'evals48@example.com'
  | 2018-10-22 21:50:00,321[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 193]  - Failed to start Kubernetes runtime of workspace workspace45og8pnovmumd34u. Cause: Timed out waiting for [0] milliseconds for [Deployment] with name:[workspace45og8pnovmumd34u.dockerimage] in namespace [che].
  | 2018-10-22 21:50:00,767[aceSharedPool-1]  [WARN ] [i.f.k.c.i.VersionUsageUtils 55]      - The client is using resource type 'replicasets' with unstable version 'v1beta1'
  | 2018-10-22 21:50:01,136[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 391]   - Workspace 'evals48@example.com:simon-dev' with id 'workspace45og8pnovmumd34u' start failed

**Comment by sigreen** [comment]
@jasonmadigan

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13

**Comment by sigreen** [comment]
I recreated the Che pods and was able to create a single workspace.  I tried creating additional workspaces and encountered this error in the Che log:


2018-10-23 14:39:22,882[default.svc/...]  [ERROR] [.w.i.k.n.KubernetesDeployments 439]  - Failed to parse last timestamp of the event: PodEvent{podName='workspacel402z9crxk3x3dkx.dockerimage-6b878cb557-qvjxq', containerName='null', reason='FailedScheduling', message='0/6 nodes are available: 1 Insufficient memory, 2 node(s) had no available volume zone, 3 node(s) didn't match node selector.', creationTimestamp='2018-10-23T14:39:21Z', lastTimestamp='2018-10-23T14:39:22Z'}

**Comment by aidenkeating** [comment]
@sigreen Is this a duplicate of #79?

**Comment by sigreen** [comment]
This is not a duplicate but a separate issue. I retested Che again today with user4.  I noticed the following error when creating a workspace in the Che pod logs:


2018-10-24 19:40:46,826[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'user4/simon-dev' with id 'workspace8n2b2rf86hmh4o9m' created by user 'user4'
--
  | 2018-10-24 19:40:50,847[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 330]   - Starting workspace 'user4/simon-dev' with id 'workspace8n2b2rf86hmh4o9m' by user 'user4'
  | 2018-10-24 19:45:51,148[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 193]  - Failed to start Kubernetes runtime of workspace workspace8n2b2rf86hmh4o9m. Cause: Timed out waiting for [0] milliseconds for [Deployment] with name:[workspace8n2b2rf86hmh4o9m.dockerimage] in namespace [che].
  | 2018-10-24 19:45:51,367[aceSharedPool-1]  [WARN ] [i.f.k.c.i.VersionUsageUtils 55]      - The client is using resource type 'replicasets' with unstable version 'v1beta1'
  | 2018-10-24 19:45:51,687[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 391]   - Workspace 'user4:simon-dev' with id 'workspace8n2b2rf86hmh4o9m' start failed
  | 2018-10-24 19:45:57,158[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 330]   - Starting workspace 'user4/simon-dev' with id 'workspace8n2b2rf86hmh4o9m' by user 'user4'

**Comment by sigreen** [comment]
Tested 10 users concurrently, all spinning-up 5 workspaces.  Tested OK so closing issue

**Comment by jasonmadigan** [comment]
thanks for verifying @sigreen
