### ISSUE TITLE
[Intergreatly] - Update Microcks version

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#78]
Per https://github.com/microcks/microcks/issues/64, the microcks team fixed an issue for us yesterday, and we need to update the integreatly env to use the version that is described in the issue.

**Comment by VinayBhalerao** [comment]
cc @aidenkeating @maleck13

**Comment by VinayBhalerao** [comment]
https://github.com/microcks/microcks/milestone/3

**Comment by aidenkeating** [comment]
@VinayBhalerao From looking at https://hub.docker.com/r/microcks/microcks/tags/ there doesn't seem to be a new tag released, but `master` has been updated. The installer references `master` already (https://github.com/jbossdemocentral/3scale-api-workshop/blob/master/support/templates/microcks-template.yml#L75).

The demo2 cluster already has the latest image (`d8a1819b273b67bd797ed08518b2d786d9a3d3e40483acffa8e8cb08be3f86db`)

Is there any other work to be done here?

**Comment by VinayBhalerao** [comment]
I didn't realize that our cluster already had the updated `master` from microcks after the bug was fixed.

Verified microcks/microcks#64 on our cluster, and it works as expected.

Thanks for checking @aidenkeating. Closing.
