### ISSUE TITLE
Unable to provision services using user1..50 login via https://tutorial-web-app-webapp.integreatly-demo2.opentry.me

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-integration#80]
When I navigate to https://tutorial-web-app-webapp.integreatly-demo2.opentry.me/ and login using user1..50 credentials, the following OpenShift project gets spun off:

user1-walkthrough-projects

If I examine the che / fuse / launcher / 3scale provisioned services, I notice the following error:

The service is not yet ready. The instance references a ClusterServiceClass that does not exist. References a non-existent ClusterServiceClass {ClassExternalName:"fuse"} or there is more than one (found: 0)

**Comment by sigreen** [comment]
@jasonmadigan @aidenkeating @maleck13

**Comment by aidenkeating** [comment]
Found the issue in the Integreatly installer. Will make a PR.

@sigreen I've reprovisioned the MSB for the demo2 cluster for now which should resolve the issue for now.

**Comment by sigreen** [comment]
Retested with User3.  Fuse, Che and 3scale tested OK
