### ISSUE TITLE
[Integreatly] - Project link is not showing in the WebApp 

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-integration#83]
3scale Apicurio, Microcks and Gogs are missing from the web page

https://userX-admin.dil.opentry.me/p/login
http://apicurio-studio.dil.opentry.me
http://microcks.dil.opentry.me
http://gogs.dil.opentry.me/

<img width="1680" alt="screen shot 2018-10-24 at 10 53 28 am" src="https://user-images.githubusercontent.com/2534483/47439912-34b49800-d77b-11e8-8757-d5906d6e53ac.png">

@jasonmadigan @aidenkeating @maleck13

**Comment by jasonmadigan** [comment]
thanks @weimeilin79 - tracking on an Integreatly Trello - will update this GH issue when there's a new version of the web-app with the ability to add custom links
