### ISSUE TITLE
Citizen Integrator Step 2 - update description

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#85]
Step says "Different from other API editor products, Apicurio's Editor is a graphical, form-based editor". May want to tone down statement to be more factual "Apicurio is a graphical, form-based API editor.

concern may cause an objection early from someone in audience about other API editors which would be needlessly distracting from core focus on workshop...

**Comment by sigreen** [comment]
Modified integrator lab01 to reflect this change.
