### ISSUE TITLE
Citizen integration - Step 11

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#87]
Add a description comment

![apicurio_studio_-_api_editor____locations_user_32](https://user-images.githubusercontent.com/7827135/47442111-9ae2f000-d766-11e8-8430-396dc6f722d9.png)
 for the Response 200OK or it throws an error like below

**Comment by VinayBhalerao** [comment]
Same for the `POST` method at step 20

**Comment by VinayBhalerao** [comment]
Same for `GET /locations/{id}` for step 30

**Comment by sigreen** [comment]
Working on this fix

**Comment by sigreen** [comment]
Closing as this issue is now resolved
