### ISSUE TITLE
Review Lab # 1 - Integration Track

### ISSUE THREAD

**Issue by yossiko24** [RedHatWorkshops/dayinthelife-integration#9]
Step 0: Deploy and configure your API management platform 
Step 1: Deploy and configure your API gateway
Step 2: Setup the pipelines

Note: at the end of this lab unit, the user successfully access the workshop platform, configure and setup the agile integration components and pipeline

**Comment by sigreen** [comment]
@scranton has reviewed and tested citizen integrator track end-to-end
