### ISSUE TITLE
Citizen Integrator Lab 1 Step 3 - break into multiple steps; at least one per path

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/dayinthelife-integration#96]
To much happing in this one step. Each step should have a description of what will be there after user completes step.

Right now Step 3 has you creating 3 paths, each with 1+ HTTP operations per path, and each operation has multiple steps to configure. Too many levels of context to put in a single lab step.

**Comment by sigreen** [comment]
Seperated Section 3 into three separate subsections (3a, 3b, and 3c).
